name: gokrazy appliance build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        # Latest minor release of Go 1.19:
        go-version: ^1.19

    - name: install gok CLI
      run: |
        go install github.com/gokrazy/tools/cmd/gok@main
        echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV

    - name: create new gokrazy instance
      run: gok new

    - name: add this program to the gokrazy instance
      run: gok add .

    - name: generate gokrazy disk image
      run: gok overwrite --root root.squashfs
