name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testandinstall:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Ensure we are on Go 1.16 (GitHub Actions defaults to 1.15)
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'

    - run: go version

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: run tests
      run: go test ./...

    - name: install binaries
      run: go install github.com/stapelberg/scan2drive github.com/stapelberg/scan2drive/cmd/...
